
type t =
  | NoSuchNick of Nickname.t                     [@name "401"] [@message "No such nick/channel"]
  | NoSuchServer of string                       [@name "402"] [@message "No such server"]
  | NoSuchChannel of string                      [@name "403"] [@message "No such channel"]
  | CannotSendToChan of Channel.t                [@name "404"] [@message "Cannot send to channel"]
  | TooManyChannels of Channel.t                 [@name "405"] [@message "You have joined too many channels"]
  | WasNoSuchNick of Nickname.t                  [@name "406"] [@message "There was no such nickname"]
  | TooManyTargets of string * string * string   [@name "407"] (*FIXME*)
  | NoSuchService of string                      [@name "408"] [@message "No such service"]
  | NoOrigin                                     [@name "409"] [@message "No origin specified"]
  | NoRecipient                                  [@name "411"] [@message "No recipient given"]
  | NoTextToSend                                 [@name "412"] [@message "No text to send"]
  | NoTopLevel of string                         [@name "413"] [@message "No toplevel domain specified"]
  | WildTopLevel of string                       [@name "414"] [@message "Wildcard in toplevel domain"]
  | BadMask of string                            [@name "415"] [@message "Bad server/host mask"]
  | UnknownCommand of string                     [@name "421"] [@message "Unknown command"]
  | NoMotd                                       [@name "422"] [@message "MOTD File is missing"]
  | NoAdminInfo of string                        [@name "423"] [@message "No administrative info available"]
  | FileError of string * string                 [@name "424"] (*FIXME*)
  | NoNicknameGiven                              [@name "431"] [@message "No nickname given"]
  | ErroneousNickname of string                  [@name "432"] [@message "Erroneous nickname"]
  | NicknameInUse of Nickname.t                  [@name "433"] [@message "Nickname is already in use"]
  | NickCollision of string * string * string    [@name "436"] (*FIXME*)
  | UnavailResource of string                    [@name "437"] [@message "Nick/channel is temporarily unavailable"]
  | UserNotInChannel of Nickname.t * Channel.t   [@name "441"] [@message "They aren't on that channel"]
  | NotOnChannel of Channel.t                    [@name "442"] [@message "You're not on that channel"]
  | UserOnChannel of Nickname.t * Channel.t      [@name "443"] [@message "is already on channel"]
  | NoLogin of string                            [@name "444"] [@message "User not logged in"]
  | SummonDisabled                               [@name "445"] [@message "SUMMON has been disabled"]
  | UsersDisabled                                [@name "446"] [@message "USERS has been disabled"]
  | NotRegistered                                [@name "451"] [@message "You have not registered"]
  | NeedMoreParams of string                     [@name "461"] [@message "Not enough parameters"]
  | AlreadyRegistered                            [@name "462"] [@message "Unauthorized command (already registered)"]
  | NoPermFromHost                               [@name "463"] [@message "Your host isn't among the privileged"]
  | PasswdMismatch                               [@name "464"] [@message "Password incorrect"]
  | YoureBannedCreep                             [@name "465"] [@message "You are banned from this server"]
  | YouWillBeBanned                              [@name "466"] [@message "You will be banned from this server"]
  | KeySet of Channel.t                          [@name "467"] [@message "Channel key already set"]
  | ChannelIsFull of Channel.t                   [@name "471"] [@message "Cannot join channel (+l)"]
  | UnknownMode of char * Channel.t              [@name "472"] (*FIXME*)
  | InviteOnlyChan of Channel.t                  [@name "473"] [@message "Cannot join channel (+i)"]
  | BannedFromChan of Channel.t                  [@name "474"] [@message "Cannot join channel (+b)"]
  | BadChannelKey of Channel.t                   [@name "475"] [@message "Cannot join channel (+k)"]
  | BadChanMask of Channel.t                     [@name "476"] [@message "Bad channel mask"]
  | NoChanModes of Channel.t                     [@name "477"] [@message "Channel doesn't support modes"]
  | BanListFull of Channel.t * char              [@name "478"] [@message "Channel list is full"]
  | NoPrivileges                                 [@name "481"] [@message "Permission denied- you're not an IRC operator"]
  | ChanopPrivNeeded of Channel.t                [@name "482"] [@message "You're not channel operator"]
  | CantKillServer                               [@name "483"] [@message "You can't kill a server!"]
  | Restricted                                   [@name "484"] [@message "Your connection is restricted!"]
  | UniqOpPrivNeeded                             [@name "485"] [@message "You're not the original channel operator"]
  | NoOperHost                                   [@name "491"] [@message "No O-lines for your host"]
  | UModeUnknownFlag                             [@name "501"] [@message "Unknown MODE flag"]
  | UsersDontMatch                               [@name "502"] [@message "Cannot change mode for other users"]

[@@deriving irc_internal_ppx]

exception Exception of t
