
type t =
  | NoSuchNick of Nickname.t                     [@repr "401"] [@addargs ["No such nick/channel"]]
  | NoSuchServer of string                       [@repr "402"] [@addargs ["No such server"]]
  | NoSuchChannel of string                      [@repr "403"] [@addargs ["No such channel"]]
  | CannotSendToChan of Channel.t                [@repr "404"] [@addargs ["Cannot send to channel"]]
  | TooManyChannels of Channel.t                 [@repr "405"] [@addargs ["You have joined too many channels"]]
  | WasNoSuchNick of Nickname.t                  [@repr "406"] [@addargs ["There was no such nickname"]]
  | TooManyTargets of string * string * string   [@repr "407"] (*FIXME*)
  | NoSuchService of string                      [@repr "408"] [@addargs ["No such service"]]
  | NoOrigin                                     [@repr "409"] [@addargs ["No origin specified"]]
  | NoRecipient                                  [@repr "411"] [@addargs ["No recipient given"]]
  | NoTextToSend                                 [@repr "412"] [@addargs ["No text to send"]]
  | NoTopLevel of string                         [@repr "413"] [@addargs ["No toplevel domain specified"]]
  | WildTopLevel of string                       [@repr "414"] [@addargs ["Wildcard in toplevel domain"]]
  | BadMask of string                            [@repr "415"] [@addargs ["Bad server/host mask"]]
  | UnknownCommand of string                     [@repr "421"] [@addargs ["Unknown command"]]
  | NoMotd                                       [@repr "422"] [@addargs ["MOTD File is missing"]]
  | NoAdminInfo of string                        [@repr "423"] [@addargs ["No administrative info available"]]
  | FileError of string * string                 [@repr "424"] (*FIXME*)
  | NoNicknameGiven                              [@repr "431"] [@addargs ["No nickname given"]]
  | ErroneousNickname of string                  [@repr "432"] [@addargs ["Erroneous nickname"]]
  | NicknameInUse of Nickname.t                  [@repr "433"] [@addargs ["Nickname is already in use"]]
  | NickCollision of string * string * string    [@repr "436"] (*FIXME*)
  | UnavailResource of string                    [@repr "437"] [@addargs ["Nick/channel is temporarily unavailable"]]
  | UserNotInChannel of Nickname.t * Channel.t   [@repr "441"] [@addargs ["They aren't on that channel"]]
  | NotOnChannel of Channel.t                    [@repr "442"] [@addargs ["You're not on that channel"]]
  | UserOnChannel of Nickname.t * Channel.t      [@repr "443"] [@addargs ["is already on channel"]]
  | NoLogin of string                            [@repr "444"] [@addargs ["User not logged in"]]
  | SummonDisabled                               [@repr "445"] [@addargs ["SUMMON has been disabled"]]
  | UsersDisabled                                [@repr "446"] [@addargs ["USERS has been disabled"]]
  | NotRegistered                                [@repr "451"] [@addargs ["You have not registered"]]
  | NeedMoreParams of string                     [@repr "461"] [@addargs ["Not enough parameters"]]
  | AlreadyRegistered                            [@repr "462"] [@addargs ["Unauthorized command (already registered)"]]
  | NoPermFromHost                               [@repr "463"] [@addargs ["Your host isn't among the privileged"]]
  | PasswdMismatch                               [@repr "464"] [@addargs ["Password incorrect"]]
  | YoureBannedCreep                             [@repr "465"] [@addargs ["You are banned from this server"]]
  | YouWillBeBanned                              [@repr "466"] [@addargs ["You will be banned from this server"]]
  | KeySet of Channel.t                          [@repr "467"] [@addargs ["Channel key already set"]]
  | ChannelIsFull of Channel.t                   [@repr "471"] [@addargs ["Cannot join channel (+l)"]]
  | UnknownMode of char * Channel.t              [@repr "472"] (*FIXME*)
  | InviteOnlyChan of Channel.t                  [@repr "473"] [@addargs ["Cannot join channel (+i)"]]
  | BannedFromChan of Channel.t                  [@repr "474"] [@addargs ["Cannot join channel (+b)"]]
  | BadChannelKey of Channel.t                   [@repr "475"] [@addargs ["Cannot join channel (+k)"]]
  | BadChanMask of Channel.t                     [@repr "476"] [@addargs ["Bad channel mask"]]
  | NoChanModes of Channel.t                     [@repr "477"] [@addargs ["Channel doesn't support modes"]]
  | BanListFull of Channel.t * char              [@repr "478"] [@addargs ["Channel list is full"]]
  | NoPrivileges                                 [@repr "481"] [@addargs ["Permission denied- you're not an IRC operator"]]
  | ChanopPrivNeeded of Channel.t                [@repr "482"] [@addargs ["You're not channel operator"]]
  | CantKillServer                               [@repr "483"] [@addargs ["You can't kill a server!"]]
  | Restricted                                   [@repr "484"] [@addargs ["Your connection is restricted!"]]
  | UniqOpPrivNeeded                             [@repr "485"] [@addargs ["You're not the original channel operator"]]
  | NoOperHost                                   [@repr "491"] [@addargs ["No O-lines for your host"]]
  | UModeUnknownFlag                             [@repr "501"] [@addargs ["Unknown MODE flag"]]
  | UsersDontMatch                               [@repr "502"] [@addargs ["Cannot change mode for other users"]]

[@@deriving irc_internal_ppx]

exception Exception of t
